Repository ShohruhShokulov/Software-Engineering-ISE4133-Mid-Term-Project, pull requests merged in 2025-05, with the labels that each got.

#3 Add VoiceHandler and WeatherService classes for text-to-speech and we…
  src/utils/voice_handler.py
  src/utils/weather_service.py
Labels: enhancement

#2 Fuel calculator
  src/utils/favorites_manager.py
  src/utils/fuel_calculator.py
  src/utils/geocoding.py
Labels: enhancement

#5 Add MapGenerator class for generating interactive route maps
  src/utils/map_generator.py
Labels: enhancement

#6 Add TravelAssistant class for processing travel queries and generatin…
  src/main.py
  src/utils/__init__.py
  src/utils/travel_assistant.py
Labels: enhancement

#8 Update documentations and project report for Smart Travel Assistant
  README.md
  docs/Mid-term_report.docx
  docs/README.md
Labels: documentation

#9 Update VSCode configuration and fix README link
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
Labels: documentation, enhancement
